config/routes.rb
Rails.application.routes.draw do
  get 'votes/index'

  get 'votes/show'

  get 'votes/create'

  get 'votes/new'

  get 'votes/edit'

  root "questions#index"
  devise_for :users

  resources :questions

  resources :questions do
    resources :comments
  end

  resources :questions do
    resources :answers
  end


  resources :answers do
    resources :comments
  end

  resources :questions do
    resources :votes
  end

  resources :answers do
    resources :votes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable
  has_many :votes, as: :votable

  validates :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true  
  validates :description, presence: true
end

app/models/concerns/jobs/application_job.rb
class ApplicationJob < ActiveJob::Base
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  belongs_to :user

  validates :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :answers
   has_many :questions
   has_many :votes
   has_many :comments

   validates :email, uniqueness: true

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
     question = valid_params_ans
     @answer = Question.find(question[:question_id]).answers.new(valid_params_ans)
     if @answer.save
       redirect_to question_path(question[:question_id])
     else
       @errors_answer = @answer.errors.full_messages
       @question = @answer.question
       @question.reload

       render '/questions/show'
     end
  end

  private
  def valid_params_ans
    params.require(:answer).permit(:description).merge(user_id: current_user.id, question_id: params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
  	if params.key?("question_id")
	  	param_question = params[:question_id]
	  	@comment = Question.find(param_question).comments.new(valid_params_comments)
	  	if @comment.save
	  		redirect_to question_path(param_question)
	  	else
	  		@errors_comment_que = @comment.errors.full_messages
	  		@question = Question.find(param_question)
	  		render '/questions/show'
	  	end
	 else

		param_answer = params[:answer_id]
	  	@comment = Answer.find(param_answer).comments.new(valid_params_comments)
	  	if @comment.save
	  		redirect_to question_path(Answer.find(param_answer).question.id)
	  	else
        	@errors_comment_ans = @comment.errors.full_messages
        	@question = Answer.find(param_answer).question
        render '/questions/show'
	  	end
	  end
end

  private
  def valid_params_comments
  	params.require(:comment).permit(:description).merge(user_id: current_user.id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
   before_action :authenticate_user! , only: [:new]

  def index
  	@questions = Question.all
  	if params[:query].present?
  		@questions = @questions.where("title LIKE :query", query: "%#{params[:query]}%")
  	end
  end

  def new
  	@question = Question.new
  end

  def create
    @question = current_user.questions.create(valid_params)
    if @question.save
      redirect_to question_path(@question.id)
    else
    	puts @question.errors.full_messages
      @errors = @question.errors.full_messages
      puts @errors
      puts current_user
      render :new
  end
end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(valid_params)
      redirect_to question_path
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private
    def valid_params()
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    if params.key?("question_id")
      param_question = params[:question_id]
      if params[:vote][:type]=="sum"
        if is_user?(param_question,"question")
          cant_vote(param_question,"question","vote")
        else
          vote_question(param_question)
        end
      else
        if is_user?(param_question,"question")
          delete_question_vote(param_question)
        else
          cant_vote(param_question,"question","delete")
        end
      end
   else
      param_answer = params[:answer_id]
      if params[:vote][:type]=="sum"
        if is_user?(param_answer,"answer")
          cant_vote(param_answer,"answer","vote")
        else
          vote_answer(param_answer)
        end
      else
        if is_user?(param_answer,"answer")
          delete_answer_vote(param_answer)
        else
          cant_vote(param_answer,"answer","delete")
        end
      end
    end
  end

  def cant_vote(param,type,action)
    if type == "question"
      @errors_votes_q = "You can't #{action} twice this #{type}"
    else
      @errors_votes_a = "You can't #{action} twice this #{type}"
    end
    if type == "question"
      @question = Question.find(param)
      render '/questions/show'
    else
      @question = Answer.find(param).question
      render '/questions/show'
    end
  end

  def is_user?(param,type)
    if type == "question"
      Question.find(param).votes.each do |vote|
        if vote.user_id == current_user.id
          return true
        end
      end
      return false
    else
      Answer.find(param).votes.each do |vote|
        if vote.user_id == current_user.id
          return true
        end
      end
      return false
    end
  end

  def vote_question(param_question)
    @vote = Question.find(param_question).votes.new(user_id: current_user.id)
    if @vote.save
      redirect_to question_path(param_question)
    else
      @errors_vote_que = @vote.errors.full_messages
      @question = Question.find(param_question)
      render '/questions/show'
    end
  end

  def vote_answer(param_answer)
    @vote = Answer.find(param_answer).votes.new(user_id: current_user.id)
    if @vote.save
      redirect_to question_path(Answer.find(param_answer).question.id)
    else
        @errors_vote_ans = @vote.errors.full_messages
        @question = Answer.find(param_answer).question
      render '/questions/show'
    end
  end

  def delete_question_vote(param_question)
    Question.find(param_question).votes.first.destroy
      @question = Question.find(param_question)
      render '/questions/show'
  end

  def delete_answer_vote(param_answer)
    Answer.find(param_answer).votes.first.destroy
    @question = Answer.find(param_answer).question
    render '/questions/show'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    md = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    syntax_highlighter(md.render(text)).html_safe
  end

  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper

def create_vote(param_question)
	@vote = Question.find(param_question).votes.new(user_id: current_user.id)
        if @vote.save
          redirect_to question_path(param_question)
        else
          @errors_vote_que = @vote.errors.full_messages
          @question = Question.find(param_question)

        end
    end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperFlowStack</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div>
        <% if user_signed_in? %>
        <nav class="navbar navbar-light bg-light">
          <a href="/questions"><img src="/img/stack.png" class="logo rounded float-left" ></a>
          <%=form_tag questions_path, method:"GET", id: "search" do%>
            <%= text_field_tag :query %>
            <%= submit_tag "Search" %>
          <% end %>
          <a class="navbar-brand" href="/"> Bienvenido, <%= User.find_by(id: [current_user.id]).email%></a>
          <button class="btn btn-outline-success" type="button"><%=  link_to "Sign out",destroy_user_session_path, :method => 'delete'
          %></button>
        </nav>
        <% else  %>
        <nav class="navbar navbar-light bg-light">
            <a href="/questions"><img src="/img/stack.png" class="logo rounded float-left" ></a>
            <button class="btn btn-outline-success" type="button"><a href="<%= new_user_session_path %>">Log In</a></button>
            <button class="second btn btn-outline-success" type="button"><%=  link_to "Sign In", new_user_registration_path%></button>
          <%=form_tag questions_path, method:"GET", id: "search" do %>
            <%= text_field_tag :query %>
            <%= submit_tag "Search" %>
          <% end %>
        </nav>
        <% end %>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/questions/edit.html.erb
<div class="container">
  <div class="form-row ">
  <%= form_for @question do |f| %>
    <div class="col" style="margin-top:20px;">
      <%= f.label :title %><br />
      <%= f.text_field :title, class:"form-control", autofocus: true %>
    </div>

    <div class="col" style="margin-top:20px;">
      <%= f.label :description %><br />
      <%= f.text_area :description, class:"form-control", autocomplete: "off" %>
    </div>

    <div class="actions" style="margin-top:50px;float:right;">
      <%= f.submit "Send"  %>
    </div>
  <% end %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Votes</th>
        <th scope="col">Answers</th>
        <th scope="col">Views</th>
        <th scope="col">Questions</th>
      </tr>
    </thead>
  <tbody>
    <div class="ask">
    <%= link_to "Ask a new question now", new_question_path %>
    </div>
    <div>
      <%@questions.each do |question|%>
        <tr>
          <td><%=question.votes.count%></td>
          <td><%=question.answers.count%></td>
          <td> 10</td>
          <td>
            <div>
              <ul>
                <li> <p> <%= link_to question.title, question_path(question.id) %></p></li>
                <li> <p> <%= question.user.email %></p></li>
                <li> <p> <%= question.created_at%> </p></li>
              </ul>
            </div>
          </td>
        </tr>
      <%end%>
    </div>
  </tbody>
</table>
</div>

app/views/questions/new.html.erb
<div class="container">
  
  <% if @errors %>
    <% @errors.each do |error| %>
     <ul class= "errors">
       <li><%= error %></li>
     </ul>
    <% end %>
  <% end %>
  
  <div class="form-row ">
  <%= form_for @question do |f| %>
    <div class="col">
      <%= f.label :title %><br />
      <%= f.text_field :title, class:"form-control", autofocus: true %>
    </div>

    <div class="col">
      <%= f.label :description %><br />
      <%= f.text_area :description, class:"form-control", autocomplete: "off" %>
    </div>

    <div class="actions" style="margin-top:50px;float:right">
      <%= f.submit "Send Question"  %>
    </div>
  <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="container">
  <div class="btn-all">
    <%if current_user == @question.user%>
      <div class="btn-edit">
        <%=link_to "Edit Question",edit_question_path(@question.id)%>
      </div>
    <% end %>

    <div class="btn-question">
      <%=link_to "Ask Question" , new_question_path%>
    </div>
  </div>

    <div class ="emailandcreated">
      <h5>User: <%= @question.user.email %></h5>
      <h5>Created: <%= @question.created_at %></h5>
    </div>
    <h1><%=markdown(@question.title)%></h1>


  <div class="description">
  <p><%= markdown(@question.description)%></p>
  </div>
  <% if (@errors_comment_que) %>
      <% @errors_comment_que.each do |error| %>
        <ul class= "errors">
          <li><%= error %></li>
        </ul>
      <% end %>
    <% end %>

    <% if @errors_votes_q %>
     <p class="alert alert-danger"> <%= @errors_votes_q %></p>
    <% end %>

  <%if current_user%>
    <div class="votes">
      <div class="">
        <%= form_for [@question, @question.votes.new] do |f| %>
        <%= f.hidden_field  :type, value: "sum"%>
        <%= f.submit "Vote +" %>
        <% end %>
      </div>
  <% end %>

    <p>Votes = <%=  @question.votes.count%></p>

  <%if current_user%>
      <div class="">
        <%= form_for [@question, @question.votes.new] do |f| %>
        <%= f.hidden_field  :type, value: "rest" %>
        <%= f.submit "Vote -" %>
        <% end %>
      </div>
    </div>
  <% end %>

  <h5> Total comments: <%=  @question.comments.count%></h5>

  <%@question.comments.each do |comment|%>
  <div class="allcomments">
    <div class="commentdescription">
      <p><%=markdown(comment.description)%></p>
    </div>
    <div class= "commentsmail">
      <p>User:<%=comment.user.email%></p>
      <p>Creaded:<%=comment.created_at%></p>
    </div>
  </div>
  <%end%>

  <% if user_signed_in? %>

    <div class="form-row ">
        <%= form_for [@question, @question.comments.new] do |f| %>

      <div class="col">
        <%= f.label :"Give us a comment" %><br />
        <%= f.text_area :description, class:"form-control", autocomplete: "off" %>
      </div>

      <div class="send">
        <%= f.submit "Send Comment Question" %>
      </div>
    <% end %>
    </div>
   <% end %>

  <div class="answer">
    <% if (@errors_comment_ans) %>
      <% @errors_comment_ans.each do |error| %>
        <ul class= "errors">
          <li><%= error %></li>
        </ul>
      <% end %>
    <% end %>

    <%@question.answers.each do |answer|%>
      <div class="answer_2">
          <h1><%=markdown(answer.description)%></h1>
        <div class="inline">
          <p>User:<%=answer.user.email%></p>
          <p>Created:<%=answer.created_at%></p>
        </div>
      </div>

      <% if @errors_votes_a %>
       <p class="alert alert-danger"> <%= @errors_votes_a %></p>
      <% end %>

      <div class="btn-votes">
        <%if current_user%>
          <div class= "votes">
            <%= form_for [answer, answer.votes.new] do |f| %>
            <%= f.hidden_field  :type, value: "sum"%>
            <%= f.submit "Vote +" %>
            <% end %>
        <% end %>

        <p>Votes = <%=  answer.votes.count%></p>

        <%if current_user%>
            <%= form_for [answer, answer.votes.new] do |f| %>
            <%= f.hidden_field  :type, value: "rest" %>
            <%= f.submit "Vote -" %>
            <% end %>
        <% end %>
      </div>

      <%answer.comments.each do |comment|%>
      <div class = "comments">
        <p><%=markdown(comment.description)%></p>
      </div>
        <div class="inline">
          <p><%= comment.user.email %></p>
          <p><%= comment.created_at %></p>
        </div>
      <%end%>

      <% if user_signed_in? %>
            <div class="form-row ">
              <%= form_for [answer, answer.comments.new] do |f| %>
                <div class="col">
                  <%= f.label :"Post your comment" %><br />
                  <%= f.text_area :description, class:"form-control", autocomplete: "off" %>
                </div>

                <div class="send">
                  <%= f.submit "Send Comment Answer" %>
                </div>
              <% end %>
              </div>
        <%end%>
    <%end%>
  </div>

  <% if @errors_answer %>
    <% @errors_answer.each do |error| %>
     <ul class= "errors">
       <li><%= error %></li>
     </ul>
    <% end %>
  <% end %>


  <% if user_signed_in? %>
  <div>
    <div class="form-row ">
      <%= form_for [@question, @question.answers.new] do |f| %>
      <div class="col">
        <%= f.label :"Post your answer" %><br />
        <%= f.text_area :description, class:"form-control", autocomplete: "off" %>
      </div>
      <div class="send">
        <%= f.submit "Send Answer" %>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
  <%if current_user == @question.user%>
    <div class="btn-delete">
      <button><%=link_to "Delete Question" , question_path(@question.id), method:"delete"%></button>
    </div>
  <%end%>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/edit.html.erb
<h1>Votes#edit</h1>
<p>Find me in app/views/votes/edit.html.erb</p>

app/views/votes/index.html.erb
<h1>Votes#index</h1>
<p>Find me in app/views/votes/index.html.erb</p>

app/views/votes/new.html.erb
<h1>Votes#new</h1>
<p>Find me in app/views/votes/new.html.erb</p>

app/views/votes/show.html.erb
<h1>Votes#show</h1>
<p>Find me in app/views/votes/show.html.erb</p>